### ISSUE TITLE
Retrieving the basic info

### ISSUE THREAD

**Issue by FinalFrase** [bitpay/php-bitpay-client-v2#22]
I've spent some time reading the BitPaySDK\Tests, and I've tried creating a "testShouldGetInvoiceId()" type of invoice. After performing the following two methods:
$basicInvoice = $this->client->createInvoice($invoice);
$retrievedInvoice = $this->client->getInvoice($basicInvoice->getId());
and doing a var_dump of each, I've noticed that even though I've set the 

$invoice->setFullNotifications(true);
$invoice->setTransactionSpeed("medium");
$invoice->setNotificationURL(URL::to('notification'));
$invoice->setNotificationEmail("example@gmail.com");

the $retrievedInvoice results default to:
#_notificationURL: ""
#_transactionSpeed: ""
#_fullNotifications: false
#_notificationEmail: ""

Is this an expected behaviour? Because I don't get any notifications on either my email nor the notificationURL.

**Comment by anbugal** [comment]
Those keys are used to create the invoice but they are not returned, the reason why you see them there is because they are part of the Invoice model, which is used for both create and retrieve invoices so yes, it is the expected behaviour.

Regarding the setNotificationEmail, you will get a notification on this email address when the consumer pays the invoice.

To understand how the IPN work and how to use the *setNotificationURL* property, please, go to https://bitpay.com/docs/invoice-callbacks
If you want to try the IPNs, you can use the open service https://hookbin.com/
