### ISSUE TITLE
Example code doesn't work

### ISSUE THREAD

**Issue by zerocarbthirty** [bitpay/php-bitpay-client-v2#52]
Hi,
I followed the instructions here:

https://support.bitpay.com/hc/en-us/articles/115003001063-How-do-I-configure-and-use-the-BitPay-PHP-Library-

and created this script:

```
<?php
require_once('vendor/autoload.php');
$bitpay = BitPaySDK\Client::create()->withFile("BitPay.config.json");
$invoice = $bitpay->createInvoice(new Invoice(50.0, "USD"));
$invoiceUrl = $invoice->getURL();
$status = $invoice->getStatus();
```

When I run the code it simply says: PHP Fatal error:  Uncaught Error: Class 'Invoice'

Do I have to include the invoicing SDK separately or put in use statements for it?

I installed this: "bitpay/sdk": "~3.0" via composer

**Comment by anbugal** [comment]
Hi @zerocarbthirty,

You need to add the Invoice model as dependency. What framework are you using?

**Comment by zerocarbthirty** [comment]
Its just a flat PHP script.

**Comment by anbugal** [comment]
In that case you need to make sure you load all the required dependencies. You can use the functional [test](https://github.com/bitpay/php-bitpay-client-v2/blob/master/tests/BitPaySDK/BitPayTest.php) included in this repo for guidance.

Im am closing this issue since it does no represent a real issue in this repo.

**Comment by zerocarbthirty** [comment]
It does however point out that the example code is wrong which is exactly
why I opened the issue in the first place.
